### ISSUE TITLE
Rails failed to initialize

### ISSUE THREAD

**Issue by pro9code** [polish-penguin-dev/Fake-Discord-Messages-V2#1]

**Comment by penguins184** [comment]
Could you please elaborate?

**Comment by pro9code** [comment]
I went to fakediscordmsgs.pingwinco.xyz
And it says application failed to respond

**Comment by penguins184** [comment]
Oh, sorry about that! Didn't write it on the repository but FDM is temporarily down until the 6th. It'll be back up soon - 6 or 7th of Jan.
